name: CI

on:
  push:
    branches: [ "homework4", "main" ]
  pull_request:
    branches: [ "homework4", "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up environment
      run: |
        mkdir -p bin
        sudo apt-get update
        sudo apt-get install -y bc
    
    - name: Build all exercises
      run: make
    
    - name: Test exercise 1
      run: make test1
    
    - name: Test exercise 2
      run: make test2
    
    - name: Test exercise 3
      run: make test3
    
    - name: Test exercise 4
      run: make test4
    
    - name: Test exercise 5
      run: make test5
